import re

from config.settings import get_digital_product_commerce_settings
from db.connection import _add_returning_id
from db.schema import SCHEMA_SQL


COMMERCE_ENV_KEYS = (
    "PAYOS_CLIENT_ID",
    "PAYOS_API_KEY",
    "PAYOS_CHECKSUM_KEY",
    "DIGITAL_PRODUCT_COOKIE_SECRET",
    "DIGITAL_PRODUCT_STORAGE_DIR",
    "DIGITAL_PRODUCT_SALES_ENABLED",
)


def _clear_commerce_env(monkeypatch):
    for key in COMMERCE_ENV_KEYS:
        monkeypatch.delenv(key, raising=False)


def _set_ready_commerce_env(monkeypatch, storage_dir):
    monkeypatch.setenv("DIGITAL_PRODUCT_SALES_ENABLED", "1")
    monkeypatch.setenv("DIGITAL_PRODUCT_STORAGE_DIR", str(storage_dir))
    monkeypatch.setenv("PAYOS_CLIENT_ID", " client ")
    monkeypatch.setenv("PAYOS_API_KEY", " api ")
    monkeypatch.setenv("PAYOS_CHECKSUM_KEY", " checksum ")
    monkeypatch.setenv("DIGITAL_PRODUCT_COOKIE_SECRET", f" {'x' * 64} ")


def test_commerce_settings_default_to_sales_disabled(monkeypatch):
    _clear_commerce_env(monkeypatch)

    settings = get_digital_product_commerce_settings()

    assert settings.sales_enabled is False
    assert settings.ready_for_checkout is False


def test_enabled_sales_require_all_secrets_and_absolute_storage(monkeypatch, tmp_path):
    _clear_commerce_env(monkeypatch)
    _set_ready_commerce_env(monkeypatch, tmp_path)

    settings = get_digital_product_commerce_settings()

    assert settings.ready_for_checkout is True
    assert settings.payos_client_id == "client"
    assert settings.payos_api_key == "api"
    assert settings.payos_checksum_key == "checksum"
    assert settings.cookie_secret == "x" * 64


def test_enabled_sales_fail_closed_for_relative_storage(monkeypatch):
    _clear_commerce_env(monkeypatch)
    _set_ready_commerce_env(monkeypatch, "relative/products")

    assert get_digital_product_commerce_settings().ready_for_checkout is False


def test_enabled_sales_fail_closed_for_short_cookie_secret(monkeypatch, tmp_path):
    _clear_commerce_env(monkeypatch)
    _set_ready_commerce_env(monkeypatch, tmp_path)
    monkeypatch.setenv("DIGITAL_PRODUCT_COOKIE_SECRET", "x" * 63)

    assert get_digital_product_commerce_settings().ready_for_checkout is False


def test_commerce_settings_repr_redacts_secret_values(monkeypatch, tmp_path):
    _clear_commerce_env(monkeypatch)
    _set_ready_commerce_env(monkeypatch, tmp_path)

    settings_repr = repr(get_digital_product_commerce_settings())

    assert "api" not in settings_repr
    assert "checksum" not in settings_repr
    assert "x" * 64 not in settings_repr


def _table_sql(schema_sql, table_name):
    match = re.search(
        rf"CREATE TABLE IF NOT EXISTS {table_name} \((.*?)\);",
        schema_sql,
        flags=re.S | re.I,
    )
    assert match is not None
    return match.group(1)


def test_order_schema_contains_security_and_expiry_fields():
    order_sql = _table_sql(SCHEMA_SQL, "digital_product_orders")

    for column in (
        "public_id",
        "recovery_token_hash",
        "expected_amount",
        "payos_order_code",
        "payment_expires_at",
        "download_expires_at",
        "download_count",
    ):
        assert column in order_sql
    assert "email" not in order_sql
    assert "phone" not in order_sql


def test_order_schema_uses_postgres_identity_and_timezone_aware_dates():
    order_sql = _table_sql(SCHEMA_SQL, "digital_product_orders")
    event_sql = _table_sql(SCHEMA_SQL, "digital_product_order_events")

    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in order_sql
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in event_sql
    assert "TIMESTAMP " not in order_sql
    assert "TIMESTAMPTZ" in order_sql
    assert "TIMESTAMPTZ" in event_sql


def test_order_status_constraint_is_closed():
    order_sql = _table_sql(SCHEMA_SQL, "digital_product_orders")
    match = re.search(r"CHECK\s*\(\s*status\s+IN\s*\((.*?)\)\s*\)", order_sql, re.S | re.I)

    assert match is not None
    assert set(re.findall(r"'([^']+)'", match.group(1))) == {
        "pending",
        "paid",
        "expired",
        "cancelled",
        "payment_review",
    }


def test_order_schema_indexes_status_expiry_and_event_foreign_key():
    assert (
        "CREATE INDEX IF NOT EXISTS idx_digital_product_orders_status_expiry"
        in SCHEMA_SQL
    )
    assert "ON digital_product_orders(status, payment_expires_at)" in SCHEMA_SQL
    assert (
        "CREATE INDEX IF NOT EXISTS idx_digital_product_order_events_order_id"
        in SCHEMA_SQL
    )
    assert "ON digital_product_order_events(order_id)" in SCHEMA_SQL


def test_order_insert_adapter_returns_generated_ids():
    for table_name in ("digital_product_orders", "digital_product_order_events"):
        sql = _add_returning_id(f"INSERT INTO {table_name} (created_at) VALUES (?)")
        assert sql.endswith("RETURNING id")


def test_order_migrations_are_forward_only_and_postgres_idempotent(monkeypatch):
    import db.schema as schema

    class FakeConn:
        def __init__(self):
            self.executed = []

        def execute(self, sql, params=None):
            self.executed.append(sql)
            return None

    conn = FakeConn()
    monkeypatch.setattr(schema, "_table_columns", lambda _conn, _table: set())
    for helper_name in (
        "_drop_legacy_feedback",
        "_normalize_ai_training_feedback_labels",
        "_migrate_legal_verifications",
        "_migrate_notification_log",
        "_migrate_user_favorite_listings",
        "_migrate_property_type_aliases",
    ):
        monkeypatch.setattr(schema, helper_name, lambda _conn: None)

    schema._run_migrations(conn)
    migration_sql = "\n".join(conn.executed)

    for table_name in ("digital_product_orders", "digital_product_order_events"):
        assert f"ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS" in migration_sql
    assert "ADD CONSTRAINT IF NOT EXISTS" not in migration_sql.upper()


def test_partial_order_table_migrations_restore_primary_keys():
    import db.schema as schema

    class FakeConn:
        def __init__(self):
            self.executed = []

        def execute(self, sql, params=None):
            self.executed.append(sql)

    conn = FakeConn()
    schema._migrate_digital_product_order_schema(conn)
    migration_sql = "\n".join(conn.executed)

    assert (
        "ADD CONSTRAINT digital_product_orders_pkey PRIMARY KEY (id)"
        in migration_sql
    )
    assert (
        "ADD CONSTRAINT digital_product_order_events_pkey PRIMARY KEY (id)"
        in migration_sql
    )
