"""Authentication & RBAC for Radar BDS (4-tier: guest / free / vip / admin)."""
from auth.core import (
    SESSION_COOKIE_NAME,
    SESSION_TTL_DAYS,
    TIER_ORDER,
    authenticate,
    create_session,
    create_user,
    current_tier,
    current_user,
    delete_session,
    grant_vip,
    hash_password,
    identifier_exists,
    log_audit,
    normalize_identifier,
    require_tier,
    revoke_vip,
    verify_password,
)

__all__ = [
    "SESSION_COOKIE_NAME",
    "SESSION_TTL_DAYS",
    "TIER_ORDER",
    "authenticate",
    "create_session",
    "create_user",
    "current_tier",
    "current_user",
    "delete_session",
    "grant_vip",
    "hash_password",
    "identifier_exists",
    "log_audit",
    "normalize_identifier",
    "require_tier",
    "revoke_vip",
    "verify_password",
]
